### ISSUE TITLE
Image Resize Lambda not executing

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/image-lambda#3]
`
2018-04-19T21:00:27.756Z a1f2f9a7-4414-11e8-9bf5-1f561296fcc5
{
    "errorMessage": "Stream yields empty buffer",
    "errorType": "Error",
    "stackTrace": [
        "Socket.<anonymous> (/var/task/node_modules/gm/lib/command.js:57:17)",
        "emitNone (events.js:91:20)",
        "Socket.emit (events.js:185:7)",
        "endReadableNT (_stream_readable.js:974:12)",
        "_combinedTickCallback (internal/process/next_tick.js:80:11)",
        "process._tickDomainCallback (internal/process/next_tick.js:128:9)"
    ]
}`

**Comment by matthewberryman** [comment]
Which area (pb/us/in)? Are you sure the s3 object isn’t zero sized (i.e. it did upload and what was uploaded is non-empty)? Do you happen to know the s3 key? Otherwise I can track back by datestamp

**Comment by tomasholderness** [comment]
Area is US; dev function.

The files are uploaded successfully. I'll start to add some log statements to see if I can hunt down the error.

**Comment by tomasholderness** [comment]
Solved it. This Lambda had the default memory, which causes a dependency to break. Increasing the memory solved the problem.

https://stackoverflow.com/questions/40026826/lambda-yields-empty-buffer-error-with-large-images

**Comment by matthewberryman** [comment]
Ok. Just noting that CloudWatch console allows you to filter by datestamp so that should help. I am out today but will get some time tonight (Chinese time) to take a look.

Sent from my iPhone

On 24 Apr 2018, at 00:46, Tomas Holderness <notifications@github.com<mailto:notifications@github.com>> wrote:


Area is US; dev function.

The files are uploaded successfully. I'll start to add some log statements to see if I can hunt down the error.

**Comment by matthewberryman** [comment]
Ah, I see you’ve solved it (this will teach me to read email from newest first ;)
As well as the memory limit (sorry my fault I must have set it too low) it’s also worth checking the time limit (a minute should be fine as limit)—I will review that across our areas tonight.

Also noting that increasing the memory also increases the compute (nice technical write up at https://engineering.opsgenie.com/how-does-proportional-cpu-allocation-work-with-aws-lambda-41cd44da3cac ).

Sent from my iPhone

On 24 Apr 2018, at 01:59, Tomas Holderness <notifications@github.com<mailto:notifications@github.com>> wrote:


Solved it. This Lambda had the default memory, which causes a dependency to break. Increasing the memory solved the problem.

https://stackoverflow.com/questions/40026826/lambda-yields-empty-buffer-error-with-large-images
